spring:
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 12345
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

